ignore:
  # Ignorar Interfaz en cobertura
   - "**/*.java"  
   - "**/*.java" 
#  - "src/main/java/edu/fiuba/algo3/vista/*.java"
#  - "src/main/java/edu/fiuba/algo3/controlador/*.java"
#  - */controlador/.*
#  - */vista/.*
